# Generated by Django 2.2.2 on 2021-09-09 00:07

from django.db import migrations, models
import utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210909_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, upload_to=utils.helpers.RandomFileName('blogImage')),
        ),
    ]
